version: '3.8'

services:
  api: 
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    container_name: cryptapp_api
    ports: 
      - "8000:8000"
    networks:
      - cryptapp_network
    environment:
      - REDIS_SERVER_HOST=redis_cache
      - REDIS_SERVER_PORT=6379
      - SIMPLE_SETTINGS=app.settings
    depends_on:
      - redis_cache

  celery_worker: 
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    container_name: cryptapp_celery_worker
    command: celery -A app.infrastructure.tasks worker --loglevel=INFO 
    networks:
      - cryptapp_network
    environment:
      - REDIS_SERVER_HOST=redis_cache
      - REDIS_SERVER_PORT=6379
      - SIMPLE_SETTINGS=app.settings
    depends_on:
      - api
      - redis_cache

  celery_beat: 
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    container_name: cryptapp_celery_beat
    command: celery -A app.infrastructure.tasks beat --loglevel=INFO
    networks:
      - cryptapp_network
    environment:
      - REDIS_SERVER_HOST=redis_cache
      - REDIS_SERVER_PORT=6379
      - SIMPLE_SETTINGS=app.settings
    depends_on:
      - api
      - redis_cache

  redis_cache:
    image: redis
    container_name: cryptapp_redis
    ports:
      - '6379:6379'
    networks:
      - cryptapp_network

networks:
  cryptapp_network:
    driver: bridge
