
services:
  run_tests: 
    build:
      context: ./../
      dockerfile: ./deployments/DockerfileRunTests
    ports: 
      - 8000:8000
    networks:
      - test_cryptapp_network
    environment:
      - REDIS_SERVER_HOST=test_redis_cache
      - REDIS_SERVER_PORT=6379

  test_redis_cache:
    image: redis
    expose:
      - 6379
    networks:
      - test_cryptapp_network

networks:
  test_cryptapp_network:
    driver: bridge
