version: '3.8' # o la versión que estés usando

services:
  api: 
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - db_data:/app/db.sqlite3
    networks:
      - cryptapp_network
    environment:
      - REDIS_SERVER_HOST=redis_cache
      - REDIS_SERVER_PORT=6379
      - SIMPLE_SETTINGS=app.settings

  redis_cache:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - cryptapp_network

networks:
  cryptapp_network:
    driver: bridge


volumes:
  db_data: